packages:
  - app
  - lib
  - packages/*

catalog:
  "@open-wc/testing": ^4.0.0
  "@playwright/test": ^14.1.6
  "@vitest/coverage-v8": ^2.1.2
  "@vitest/ui": ^2.1.2
  "@types/node": ^22.7.5
  esbuild: ^0.24.0
  esbuild-plugin-minify-html-literals: ^2.0.1
  jsdom: ^25.0.1
  lit: ^3.2.1
  tslib: ^2.7.0
  tsx: ^4.19.1
  typescript: ^5.6.3
  vitest: ^2.1.2
